meublog/urls.py
from django.urls import path
from . import views

app_name = 'meublog'
urlpatterns = [
    path('', views.ListarPostView.as_view(), name='listar_posts'),
    path('<slug:slug>/', views.DetalharPostView.as_view(), name='detalhe'),
    path('sharepost/<int:pk>', views.FormContatoView.as_view(), name='share_post'),
    path('comentar/<int:pk>', views.ComentarioView.as_view(), name='comentar_post'),
    path('cadastrousuario', views.CadUsuarioView.as_view(), name='cadastrouser'),
    path('login', views.LoginUsuarioView.as_view(), name='loginuser'),
    path('logout', views.LogoutUsuarioView.as_view(), name='logoutuser'),
]

meusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meublog.urls', namespace='meublog'))
]

meusite2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meublog.urls', namespace='meublog'))
]

meublog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class PublicadosManager(models.Manager):
    def get_queryset(self):
        return super(PublicadosManager, self).get_queryset().filter(status='publicado')


class Post(models.Model):
    STATUS_CHOICES = (
        ('rascunho', 'Rascunho'),
        ('publicado', 'publicado')
    )
    objects = models.Manager()
    publicado = PublicadosManager()

    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100)
    corpo = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meublog_posts')
    publicados = models.DateTimeField(default=timezone.now)
    criado = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='rascunho')

    def gwt_absolute_url(self):
        return reverse('meublog:detalhe', args=[self.slug])

    class Meta:
        ordering = ('-publicados',)
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.titulo


class Comentario(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    nome = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail')
    comentario = models.TextField('Comentário')
    criado = models.DateTimeField('Data Criação', auto_now_add=True)
    status = models.BooleanField('Ativo', default=False)

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"

    def __str__(self):
        return 'Comentado por: ' + self.nome

meublog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from meublog.models import Comentario


class EmailPost(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    destino = forms.EmailField()
    coments = forms.CharField(required=False, widget=forms.Textarea)

    def enviar_email(self, meupost):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        destino = self.cleaned_data['destino']
        coments = self.cleaned_data['coments']

        conteudo = f"Recomendo Ler o Post: {meupost.titulo}/n" \
                   f"Comentários: {coments}"
        mail = EmailMessage(
            subject=f"Recomendo este Post",
            body=conteudo,
            from_email='contato@meublog.com',
            to=[destino,],
            headers={'Reply-to': email}
        )
        mail.send()


class ComentarioModelForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['nome', 'email', 'comentario']

    def comentar(self, post):
        new_comment = self.save(commit=False)
        new_comment.post = post
        new_comment.nome = self.cleaned_data['nome']
        new_comment.email = self.cleaned_data['email']
        new_comment.comentario = self.cleaned_data['comentario']
        return new_comment.save()


class CadUsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

meublog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, DetailView, FormView, CreateView

from .forms import EmailPost, ComentarioModelForm, CadUsuarioForm
from .models import Post, Comentario


class ListarPostView(ListView):
    queryset = Post.publicado.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = "meublog/post/listarposts.html"


class DetalharPostView(DetailView):
    template_name = "meublog/post/detalharpost.html"
    model = Post

    def _get_comment(self, id_post):
        try:
            return Comentario.objects.filter(post_id=id_post, status=True)
        except Comentario.DoesNotExixt:
            raise Exception

    def get_context_data(self, **kwargs):
        context = super(DetalharPostView, self).get_context_data(**kwargs)
        context['coments'] = self._get_comment(self.object.id)
        return context


class FormContatoView(FormView):
    template_name = 'meublog/post/sharepost.html'
    form_class = EmailPost
    success_url = reverse_lazy('meublog:listar_posts')

    def get_post(self, id_post):
        try:
            return Post.publicado.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'O post não existe!')
            reverse_lazy('meublog:listar_posts')

    def get_context_data(self, **kwargs):
        context = super(FormContatoView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        form.enviar_email(meupost)
        messages.success(self.request, f"Post {meupost.titulo} enviado com sucesso!")

        return super(FormContatoView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        messages.error(self.request, f"Post {meupost.titulo} Não enviado!")

        return super(FormContatoView, self).form_invalid(form, *args, **kwargs)


class ComentarioView(CreateView):
    template_name = 'meublog/post/comentarios.html'
    form_class = ComentarioModelForm

    def get_post(self, id_post):
        try:
            return Post.publicado.get(pk=id_post)
        except Post.DoesNotExist:
            raise Exception

    def get_context_data(self, **kwargs):
        context = super(ComentarioView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        post = self.get_post(self.kwargs['pk'])
        form.comentar(post)
        return redirect('meublog:detalhe', post.slug)


class CadUsuarioView(CreateView):
    template_name = 'meublog/usuarios/cadusuario.html' # criar depois
    form_class = CadUsuarioForm
    success_url = reverse_lazy('meublog:loginuser') # criar depois

    def form_valid(self, form, *args, **kwargs):
        form.cleaned_data
        messages.success(self.request, f'Usuário Cadastrado')
        return super(CadUsuarioView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, f'Usuário Não Cadastrado!')
        return super(CadUsuarioView, self).form_invalid(form, *args, **kwargs)


class LoginUsuarioView(FormView):
    template_name = 'meublog/usuarios/login.html'
    model = User
    form_class = AuthenticationForm
    sucess_url = reverse_lazy('meublog:listar_posts')

    def form_valid(self, form):
        nome = form.cleaned_data['username']
        senha = form.cleaned_data['password']
        usuario = authenticate(self.request, username=nome, password=senha)
        if usuario is not None:
            login(self.request, usuario)
            return redirect('meublog:listar_posts')
        messages.error(self.request, f'Usuário não existe')
        return redirect('meublog:loginuser')

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, f'Login não realizado!')
        return redirect('meublog:listar_posts')

class LogoutUsuarioView(LoginRequiredMixin, LogoutView):
    def get(self, request):
        logout(request)
        return redirect('meublog:listar_posts')

meublog/templates/meublog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block titulo %} {% endblock %}</title>
    <link href="{% static 'css/meublog.css' %}" rel="stylesheet">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <div id="content">
        {% block conteudo %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2><a href="{% url 'meublog:listar_posts' %}"> Meu Blog</a></h2>
        <p>Este é meu blog</p>
        {% if user.is_anonymous %}
            <p>
                <a class="btn btn-primary" href="{% url 'meublog:cadastrouser' %}">
                    Cadastrar
                </a>
            </p>
            <p>
                <a class="btn btn-success" href="{% url 'meublog:loginuser' %}">
                    Login
                </a>
            </p>
        {% else %}
            <p>
                Usuário: <b>{{ user.username }}</b>
                <p>
                    <a class="btn btn-danger" href="{% url 'meublog:logoutuser' %}">
                        Sair
                    </a>
                </p>
            </p>
        {% endif %}
    </div>
</body>
</html>

meublog/templates/meublog/post/comentar.html
{% extends 'meublog/base.html' %}

{% block titulo %} Comentando {{ post.titulo }} {% endblock %}

{% block conteudo %}
    <h1>Comentando {{ post.titulo }} </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

meublog/templates/meublog/post/comentarios.html
{% extends 'meublog/base.html' %}

{% block titulo %} Comentando {{ post.titulo }} {% endblock %}

{% block conteudo %}
{% if user.is_authenticated %}
    <h1>Comentando no Post {{ post.titulo }} </h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="usuario">Usuario</label>
            <input type="text" id="usuario" name="nome" value="{{ user.username }}" readonly/>
        </div>
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" id="email" name="email" value="{{ user.email }}" readonly/>
        </div>
        <div class="form-group">
            <label for="comentario">Comentario</label>
            <textarea id="comentario" name="comentario" rows="6" cols="23"></textarea>
        </div>

        <div class="form-group">
            <input type="submit" value="Enviar">
        </div>
    </form>
{% else %}
    <h3 class="alert">Página disponível apenas para usuários autenticados</h3>
    <h4 class="warning">Faça login ou cadastre-se</h4>
    <p><a href="{% url 'meublog:loginuser' %}" class="btn btn-primary">Logar</a> </p>
    <p><a href="{% url 'meublog:cadastrouser' %}" class="btn btn-primary">Cadastrar</a> </p>
    <p><a href="{% url 'meublog:listar_posts' %}" class="btn btn-primary">Página Inicial</a> </p>
{% endif %}
{% endblock %}

meublog/templates/meublog/post/detalharpost.html
{% extends 'meublog/base.html' %}

{% block titulo %} {{ post.titulo }} {% endblock %}

{% block conteudo %}
    <h1> {{ post.titulo }} </h1>
    <p class="date">
        Publicado em: {{ post.publicados }} por {{ post.autor }}
    </p>
    <p>
        {{ post.corpo | linebreaks }}
    </p>
    <br>

    <h4>
        <span style="margin-right:10px; margin-left:10px">
            <a href="{% url 'meublog:share_post' post.pk %}">
                Compartilhar
            </a>
        </span>
        <span style="margin-right:10px; margin-left:10px">
            <a href="{% url 'meublog:comentar_post' post.id %}">
                Comentar
            </a>
        </span>
    </h4>
    {% for c in coments %}
        <h3>
            {{ c.nome }}
        </h3>
        <p class="date">
            {{ c.criado }}
        </p>
        <p class="date">
            {{ c.email }}
        </p>
        <p>
            {{ c.comentario }}
        </p>
    {% endfor %}
    <h4>
        <span style="margin-right:10px; margin-left:10px">
            <a href="{% url 'meublog:comentar_post' post.id %}">
                Add Comment
            </a>
        </span>
    </h4>


{% endblock %}

meublog/templates/meublog/post/listarposts.html
{% extends 'meublog/base.html' %}

{% block titulo %} << Meu Blog >> 🤡🐵 {% endblock %}

{% block conteudo %}
    <h1>Meu Blog </h1>
    {% for p in posts %}
        <h2>
            <a href=" {{ p.gwt_absolute_url }}">{{ p.titulo }}</a>
        </h2>
        <p class="date">
            Publicado em: {{ p.publicados }} por {{ p.autor }}
        </p>
        <p>
            {{ p.corpo | truncatewords:15 | linebreaks }}
        </p>
    {% endfor %}
    {% include "paginacao.html" with page=page_obj %}
{% endblock %}

meublog/templates/meublog/post/sharepost.html
{% extends 'meublog/base.html' %}

{% block titulo %} A enviar Poster {{ post.titulo }} {% endblock %}

{% block conteudo %}
    <h1>Enviar Post: {{ post.titulo }} Por Email</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

meublog/templates/meublog/usuarios/cadusuario.html
{% extends "meublog/base.html" %}

{% block titulo %} Cadastro de Usuários {% endblock %}

{% block conteudo %}

<div class="container">
    <form method="post" action="{% url 'meublog:cadastrouser' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar">
    </form>
</div>

{% endblock %}

meublog/templates/meublog/usuarios/login.html
{% extends "meublog/base.html" %}

{% block titulo %} Login {% endblock %}

{% block conteudo %}

<div class="container">
    <form method="post" action="{% url 'meublog:loginuser' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Entrar">
    </form>
</div>

{% endblock %}

meublog/templates/paginacao.html
<div class="pagination">
    <span class="step_links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous }}"> <-- </a>
        {% endif %}
        <span class="current">
            Página {{ page.number }} de {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}"> --> </a>
        {% endif %}
    </span>
</div>